#!/bin/sh

set -eu

HBLOCK_DIR='/var/lib/knot-resolver/'
HBLOCK_OUTPUT="${HBLOCK_DIR}/hblock.rpz"
HBLOCK_OUTPUT_TMP=$(mktemp)

printf '%s\n' 'Downloading blacklist zone...'

cleanup() { rm -f "${HBLOCK_OUTPUT_TMP}"; }
trap cleanup EXIT

hblock -A /etc/hblock/whitelist.list -D /etc/hblock/blacklist.list --output "${HBLOCK_OUTPUT_TMP}" --template '%D CNAME %R' --redirection '.' --comment ';' --quiet
chmod 644 "${HBLOCK_OUTPUT_TMP}"

# Replace blacklist zone if it differs
if ! cmp --silent "${HBLOCK_OUTPUT_TMP}" "${HBLOCK_OUTPUT}"; then
  mv -f "${HBLOCK_OUTPUT_TMP}" "${HBLOCK_OUTPUT}"
  # Restart Knot Resolver if it is running
fi
